/**
 * Generates one illustration per question via the Gemini image API and writes
 * them to `assets/questions/<question-id>.jpg`, then regenerates the static
 * require-map at `src/data/questionImages.ts` (Metro needs literal `require`
 * calls, so the map is code-generated rather than built at runtime).
 *
 * Usage:
 *   GEMINI_API_KEY=<key> npm run generate:images
 *
 * Already-generated images are skipped, so re-running only fills gaps; delete
 * an image file to force its regeneration. The API key is read from the
 * environment on purpose — never commit it.
 *
 * This is a build-time tool. It reads the seed array directly (not via the
 * app's `@/` aliases) so it runs cleanly under tsx.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { QUESTIONS } from '../src/data/questions';

const API_URL = 'https://generativelanguage.googleapis.com/v1beta/interactions';
const MODEL = 'gemini-3.1-flash-image';

const PROMPT_TEMPLATE =
  'Present a clear, 45° top-down isometric miniature 3D cartoon scene of ' +
  '[EVENT], with its most iconic features. Use soft, refined textures with ' +
  'realistic PBR materials and gentle, lifelike lighting and shadows. Use a ' +
  'clean, minimalistic composition with a soft, solid-colored background. ' +
  'Square 1080x1080 dimension.';

const ASSETS_DIR = path.join(__dirname, '..', 'assets', 'questions');
const MAP_FILE = path.join(__dirname, '..', 'src', 'data', 'questionImages.ts');

interface InteractionStep {
  type?: string;
  content?: Array<{ type?: string; mime_type?: string; data?: string }>;
}

function eventDescription(q: (typeof QUESTIONS)[number]): string {
  const era = q.year < 0 ? `${-q.year} BCE` : `${q.year}`;
  return `${q.title} (${era}) — ${q.subtitle}`;
}

async function generateImage(apiKey: string, event: string): Promise<Buffer> {
  const response = await fetch(API_URL, {
    method: 'POST',
    headers: { 'x-goog-api-key': apiKey, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: MODEL,
      input: [{ type: 'text', text: PROMPT_TEMPLATE.replace('[EVENT]', event) }],
      response_format: {
        type: 'image',
        mime_type: 'image/jpeg',
        aspect_ratio: '1:1',
        image_size: '1K',
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${(await response.text()).slice(0, 300)}`);
  }

  const body = (await response.json()) as { steps?: InteractionStep[] };
  for (const step of body.steps ?? []) {
    const image = step.content?.find((c) => c.type === 'image' && c.data);
    if (image?.data) return Buffer.from(image.data, 'base64');
  }
  throw new Error('response contained no image data');
}

/** Rebuild the require-map from whatever images exist on disk. */
function writeRequireMap(): number {
  const ids = QUESTIONS.map((q) => q.id).filter((id) =>
    existsSync(path.join(ASSETS_DIR, `${id}.jpg`)),
  );

  const entries = ids
    .map((id) => `  '${id}': require('../../assets/questions/${id}.jpg'),`)
    .join('\n');

  writeFileSync(
    MAP_FILE,
    `/**
 * AUTO-GENERATED by scripts/generateQuestionImages.ts — do not edit by hand.
 * Static \`require\` calls so Metro bundles each illustration; keyed by
 * question id. Questions without a generated image are simply absent.
 */
import type { ImageSourcePropType } from 'react-native';

export const QUESTION_IMAGES: Record<string, ImageSourcePropType> = {
${entries}
};

export function imageForQuestion(id: string): ImageSourcePropType | undefined {
  return QUESTION_IMAGES[id];
}
`,
  );
  return ids.length;
}

async function main(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error('GEMINI_API_KEY is not set. Aborting.');
    process.exitCode = 1;
    return;
  }

  mkdirSync(ASSETS_DIR, { recursive: true });
  const existing = new Set(readdirSync(ASSETS_DIR));

  let generated = 0;
  let failed = 0;

  for (const question of QUESTIONS) {
    const filename = `${question.id}.jpg`;
    if (existing.has(filename)) {
      console.log(`skip      ${question.id} (exists)`);
      continue;
    }

    try {
      const image = await generateImage(apiKey, eventDescription(question));
      writeFileSync(path.join(ASSETS_DIR, filename), image);
      generated += 1;
      console.log(`generated ${question.id} (${Math.round(image.length / 1024)} KB)`);
    } catch (error) {
      failed += 1;
      console.error(`FAILED    ${question.id}: ${(error as Error).message}`);
    }
  }

  const mapped = writeRequireMap();
  console.log(`\nDone: ${generated} generated, ${failed} failed, ${mapped} in require-map.`);
  if (failed > 0) process.exitCode = 1;
}

void main();
