/**
 * AUTO-GENERATED by scripts/generateQuestionImages.ts — do not edit by hand.
 * Static `require` calls so Metro bundles each illustration; keyed by
 * question id. Questions without a generated image are simply absent.
 */
import type { ImageSourcePropType } from 'react-native';

export const QUESTION_IMAGES: Record<string, ImageSourcePropType> = {
  'evt-moon-landing': require('../../assets/questions/evt-moon-landing.jpg'),
  'evt-berlin-wall': require('../../assets/questions/evt-berlin-wall.jpg'),
  'evt-french-revolution': require('../../assets/questions/evt-french-revolution.jpg'),
  'evt-magna-carta': require('../../assets/questions/evt-magna-carta.jpg'),
  'evt-us-independence': require('../../assets/questions/evt-us-independence.jpg'),
  'evt-constantinople': require('../../assets/questions/evt-constantinople.jpg'),
  'evt-columbus': require('../../assets/questions/evt-columbus.jpg'),
  'evt-russian-revolution': require('../../assets/questions/evt-russian-revolution.jpg'),
  'evt-titanic': require('../../assets/questions/evt-titanic.jpg'),
  'evt-great-fire-london': require('../../assets/questions/evt-great-fire-london.jpg'),
  'bat-hastings': require('../../assets/questions/bat-hastings.jpg'),
  'bat-waterloo': require('../../assets/questions/bat-waterloo.jpg'),
  'bat-gettysburg': require('../../assets/questions/bat-gettysburg.jpg'),
  'bat-thermopylae': require('../../assets/questions/bat-thermopylae.jpg'),
  'bat-agincourt': require('../../assets/questions/bat-agincourt.jpg'),
  'bat-stalingrad': require('../../assets/questions/bat-stalingrad.jpg'),
  'bat-trafalgar': require('../../assets/questions/bat-trafalgar.jpg'),
  'bat-actium': require('../../assets/questions/bat-actium.jpg'),
  'bat-tours': require('../../assets/questions/bat-tours.jpg'),
  'bat-bannockburn': require('../../assets/questions/bat-bannockburn.jpg'),
  'ppl-einstein': require('../../assets/questions/ppl-einstein.jpg'),
  'ppl-curie': require('../../assets/questions/ppl-curie.jpg'),
  'ppl-davinci': require('../../assets/questions/ppl-davinci.jpg'),
  'ppl-newton': require('../../assets/questions/ppl-newton.jpg'),
  'ppl-shakespeare': require('../../assets/questions/ppl-shakespeare.jpg'),
  'ppl-cleopatra': require('../../assets/questions/ppl-cleopatra.jpg'),
  'ppl-napoleon': require('../../assets/questions/ppl-napoleon.jpg'),
  'ppl-gandhi': require('../../assets/questions/ppl-gandhi.jpg'),
  'ppl-mandela': require('../../assets/questions/ppl-mandela.jpg'),
  'ppl-darwin': require('../../assets/questions/ppl-darwin.jpg'),
  'tec-printing-press': require('../../assets/questions/tec-printing-press.jpg'),
  'tec-telephone': require('../../assets/questions/tec-telephone.jpg'),
  'tec-powered-flight': require('../../assets/questions/tec-powered-flight.jpg'),
  'tec-television': require('../../assets/questions/tec-television.jpg'),
  'tec-transistor': require('../../assets/questions/tec-transistor.jpg'),
  'tec-world-wide-web': require('../../assets/questions/tec-world-wide-web.jpg'),
  'tec-iphone': require('../../assets/questions/tec-iphone.jpg'),
  'tec-chatgpt': require('../../assets/questions/tec-chatgpt.jpg'),
  'tec-steam-engine': require('../../assets/questions/tec-steam-engine.jpg'),
  'tec-nuclear-reactor': require('../../assets/questions/tec-nuclear-reactor.jpg'),
};

export function imageForQuestion(id: string): ImageSourcePropType | undefined {
  return QUESTION_IMAGES[id];
}
